apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javaee-cafe
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      name: javaee-cafe
      labels:
        app: javaee-cafe
    spec:
      containers:
      - name: javaee-cafe
        image: <your Docker Hub account>/javaee-cafe:v1
---
apiVersion: v1
kind: Service
metadata:
  name: javaee-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: javaee-cafe